VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IArrayGenerator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function getOneDimensionalArray(length As Long) As Variant()

End Function

Public Function getMultidimensionalArray(length As Long) As Variant()

End Function

Public Function getJaggedArray(length As Long) As Variant()

End Function



