VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IArrayGenerator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'@Folder("Tests.Dependencies.IArrayGenerator.Implementations")

Public Function getOneDimensionalArray(Length As Long) As Variant()

End Function

Public Function getMultidimensionalArray(Length As Long) As Variant()

End Function

Public Function getJaggedArray(Length As Long) As Variant()

End Function



